name: theveggieladies
favicon: null
layout_spectrum: 0.2234673190396279
typography_spectrum: 0.511835120851174
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e16938'
    - '#2a2a29'
    - '#f3f4f4'
    - '#e79675'
    - '#749347'
  brandStrength: 0.6507939132861793
  lightness: 0.9800166017375886
  saturation: 0.9221993822138757
  rhythmicContrast: 0.5504235830157995
purpose: []
